# Generated by Django 3.2.4 on 2021-06-25 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pozycja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.TextField(max_length=50)),
            ],
            options={
                'verbose_name': 'Pozycja',
                'verbose_name_plural': 'Pozycje',
            },
        ),
        migrations.CreateModel(
            name='Rola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.TextField(max_length=50)),
            ],
            options={
                'verbose_name': 'Rola',
                'verbose_name_plural': 'Role',
            },
        ),
        migrations.CreateModel(
            name='Postac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('opis', models.CharField(max_length=2000)),
                ('kod', models.CharField(max_length=10)),
                ('nazwaP', models.CharField(max_length=100)),
                ('opisP', models.CharField(max_length=500)),
                ('nazwaQ', models.CharField(max_length=100)),
                ('opisQ', models.CharField(max_length=500)),
                ('nazwaW', models.CharField(max_length=100)),
                ('opisW', models.CharField(max_length=500)),
                ('nazwaE', models.CharField(max_length=100)),
                ('opisE', models.CharField(max_length=500)),
                ('nazwaR', models.CharField(max_length=100)),
                ('opisR', models.CharField(max_length=500)),
                ('pozycja', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='leage.pozycja')),
                ('rola', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='leage.rola')),
            ],
            options={
                'verbose_name': 'Postać',
                'verbose_name_plural': 'Postacie',
            },
        ),
    ]
